"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

import version

APP = ['app/appstart.py']
DATA_FILES = [('', ['conf']),
              ('', ['img'])]
OPTIONS = dict(py2app=dict(
    plist=dict(
        NSHumanReadableCopyright="© gendan vehnberk",
        CFBundleIconFile="img/gator.icns"
    ),
))

setup(
    app=APP,
    data_files=DATA_FILES,
    options=OPTIONS,
    setup_requires=['py2app'],
    name='Gator',
    version=version.__version__,
    py_modules=['version'],
    packages=['app', 'bdbs', 'core', 'gwid'],
    url='https://anhenet.nl',
    license='Apache License 2.0',
    author='gendan vehnberk',
    description='Application for viewing and maintaining images',
    install_requires=['pyqt5', 'exifread', 'bsddb3']
)
